name: news_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.0
  equatable: ^2.0.5
  animated_text_kit: ^4.2.2
  kartal: ^2.8.0
  firebase_auth: ^4.6.3
  firebase_ui_auth: ^1.4.3
  firebase_ui_oauth_google: ^1.2.3
  shared_preferences: ^2.1.2
  responsive_framework: 0.2.0
  responsive_builder: ^0.7.0
  image_picker: ^0.8.9
  firebase_storage: ^11.2.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  very_good_analysis: ^4.0.0+1
  responsive_builder: ^0.7.0
flutter:
  uses-material-design: true

  assets:
    - assets/icon/  
  
