// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL3lVAbJM82Mx5bVnKlzw0mEclO6m2-_0',
    appId: '1:628027324735:web:baccc5d833f6ba1cb43b8a',
    messagingSenderId: '628027324735',
    projectId: 'news-app-98b4d',
    authDomain: 'news-app-98b4d.firebaseapp.com',
    storageBucket: 'news-app-98b4d.appspot.com',
    measurementId: 'G-6GH3XLH31T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4WId2vFrnISudEzfG5ZbYN_YmR2JDt8U',
    appId: '1:628027324735:android:4e4b9cf253f1a342b43b8a',
    messagingSenderId: '628027324735',
    projectId: 'news-app-98b4d',
    storageBucket: 'news-app-98b4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3AkzgL7XrNn34bK1vWcD2PAP55tjPkmg',
    appId: '1:628027324735:ios:492e89e8d1186e1eb43b8a',
    messagingSenderId: '628027324735',
    projectId: 'news-app-98b4d',
    storageBucket: 'news-app-98b4d.appspot.com',
    iosClientId: '628027324735-73nek6bn59k0bovc0a9mfkeseblcs02f.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3AkzgL7XrNn34bK1vWcD2PAP55tjPkmg',
    appId: '1:628027324735:ios:492e89e8d1186e1eb43b8a',
    messagingSenderId: '628027324735',
    projectId: 'news-app-98b4d',
    storageBucket: 'news-app-98b4d.appspot.com',
    iosClientId: '628027324735-73nek6bn59k0bovc0a9mfkeseblcs02f.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );
}
